name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2.1.1
      name: Run commands
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: |
          docker login -u johnjones4 -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          cd server && docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}
          docker push ghcr.io/${{ github.repository }}:latest
